// Generates each client's copy of the WeShopAlot design tokens from tokens.json.
//
//   Angular: Client/src/styles/_tokens.scss          (Sass variables + a mixin for CSS custom properties)
//   WPF:     WeShopAlot.UI.ClientWPF/Resources/Tokens.xaml (colors, brushes, fonts, sizes, corner radii)
//
// Run from anywhere (PowerShell):  node C:\projects\WeShopAlot\Solution\DesignSystem\build-tokens.mjs
// No packages needed. Never edit the generated files by hand: change tokens.json and run this again.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const solution = join(here, '..');
const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const pascal = (s) => s[0].toUpperCase() + s.slice(1);
const banner = 'GENERATED by Solution/DesignSystem/build-tokens.mjs from tokens.json. Do not edit by hand.';
const fallback = { heading: "'Arial Narrow', sans-serif", body: "'Segoe UI', system-ui, sans-serif" };

// ------------------------------------------------------------------ Angular (Sass)

function scss() {
  const vars = [];
  const props = [];
  const add = (group, key, value) => {
    const name = `ws-${kebab(group)}-${kebab(key)}`;
    vars.push(`$${name}: ${value};`);
    props.push(`  --${name}: #{$${name}};`);
  };
  for (const [k, v] of Object.entries(tokens.color)) add('color', k, v);
  for (const [k, v] of Object.entries(tokens.font)) add('font', k, `'${v}', ${fallback[k]}`);
  for (const [k, v] of Object.entries(tokens.fontSize)) add('font-size', k, `${v}px`);
  for (const [k, v] of Object.entries(tokens.radius)) add('radius', k, `${v}px`);
  for (const [k, v] of Object.entries(tokens.space)) add('space', k, `${v}px`);
  for (const [k, v] of Object.entries(tokens.layout)) add('layout', k, `${v}px`);
  for (const [k, v] of Object.entries(tokens.effect)) add('effect', k, `${v}`);
  return `// ${banner}
// Use the $ws-* variables in Sass; styles.scss writes the same values as --ws-* CSS custom properties.

${vars.join('\n')}

@mixin ws-root-properties {
${props.join('\n')}
}
`;
}

// ------------------------------------------------------------------ WPF (XAML)

function xamlColor(hex) {
  return '#FF' + hex.replace('#', '').toUpperCase();
}

function xaml() {
  const lines = [];
  lines.push('    <!-- Colors and brushes: {Key}Color and {Key}Brush -->');
  for (const [k, v] of Object.entries(tokens.color)) {
    lines.push(`    <Color x:Key="${pascal(k)}Color">${xamlColor(v)}</Color>`);
    lines.push(`    <SolidColorBrush x:Key="${pascal(k)}Brush" Color="${xamlColor(v)}"/>`);
  }
  const overlay = Math.round(tokens.effect.overlayOpacity * 255).toString(16).padStart(2, '0').toUpperCase();
  lines.push(`    <SolidColorBrush x:Key="OverlayBrush" Color="#${overlay}${tokens.color.ink.replace('#', '').toUpperCase()}"/>`);
  lines.push('');
  lines.push('    <!-- Fonts: Barlow and Barlow Condensed are compiled into the app (Fonts folder, SIL Open Font License) -->');
  for (const [k, v] of Object.entries(tokens.font)) {
    lines.push(`    <FontFamily x:Key="${pascal(k)}Font">pack://application:,,,/Fonts/#${v}</FontFamily>`);
  }
  lines.push('');
  lines.push('    <!-- Font sizes, spacing and layout sizes (device-independent pixels) -->');
  for (const [k, v] of Object.entries(tokens.fontSize)) lines.push(`    <sys:Double x:Key="FontSize${pascal(k)}">${v}</sys:Double>`);
  for (const [k, v] of Object.entries(tokens.space)) lines.push(`    <sys:Double x:Key="Space${pascal(k)}">${v}</sys:Double>`);
  for (const [k, v] of Object.entries(tokens.layout)) lines.push(`    <sys:Double x:Key="${pascal(k)}">${v}</sys:Double>`);
  lines.push('');
  lines.push('    <!-- Corner radii -->');
  for (const [k, v] of Object.entries(tokens.radius)) lines.push(`    <CornerRadius x:Key="Radius${pascal(k)}">${v}</CornerRadius>`);
  return `<!-- ${banner} -->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:sys="clr-namespace:System;assembly=mscorlib">
${lines.join('\n')}
</ResourceDictionary>
`;
}

const crlf = (text) => text.replace(/\r?\n/g, '\r\n');
const outputs = [
  [join(solution, 'Client', 'src', 'styles', '_tokens.scss'), scss()],
  [join(solution, 'WeShopAlot.UI.ClientWPF', 'Resources', 'Tokens.xaml'), xaml()]
];
for (const [path, text] of outputs) {
  writeFileSync(path, crlf(text), 'utf8');
  console.log('wrote ' + path);
}
