//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/Cboss.DataTransferTokenizer.Application.P" +
        "resentation")]
    public partial class NotFoundFault : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cboss.com/DataTransferTokenizer/1.0", ConfigurationName="ServiceReference1.Tokenization")]
    public interface Tokenization
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/Detokenize", ReplyAction="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/DetokenizeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.NotFoundFault), Action="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/DetokenizeNotFoundFau" +
            "ltFault", Name="NotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/Cboss.DataTransferTokenizer.Application.P" +
            "resentation")]
        System.Threading.Tasks.Task<string> DetokenizeAsync(System.Guid token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/Tokenize", ReplyAction="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/TokenizeResponse")]
        System.Threading.Tasks.Task<System.Guid> TokenizeAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TokenizationChannel : ServiceReference1.Tokenization, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TokenizationClient : System.ServiceModel.ClientBase<ServiceReference1.Tokenization>, ServiceReference1.Tokenization
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TokenizationClient(EndpointConfiguration endpointConfiguration) : 
                base(TokenizationClient.GetBindingForEndpoint(endpointConfiguration), TokenizationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenizationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TokenizationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenizationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TokenizationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TokenizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> DetokenizeAsync(System.Guid token)
        {
            return base.Channel.DetokenizeAsync(token);
        }
        
        public System.Threading.Tasks.Task<System.Guid> TokenizeAsync(string data)
        {
            return base.Channel.TokenizeAsync(data);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Tokenization))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_Tokenization))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Tokenization))
            {
                return new System.ServiceModel.EndpointAddress("https://beta.payments.cboss.com/Services/DataTransfer/1.0/PublicTokenization.svc/" +
                        "basic");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_Tokenization))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("https://beta.payments.cboss.com/Services/DataTransfer/1.0/PublicTokenization.svc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Tokenization,
            
            WSHttpBinding_Tokenization,
        }
    }
}
