DROP TABLE IF EXISTS WSA.AppUser
DROP TABLE IF EXISTS WSA.OrderItem
DROP TABLE IF EXISTS WSA.[Order]
DROP TABLE IF EXISTS WSA.[Address]
DROP TABLE IF EXISTS WSA.BasketItem
DROP TABLE IF EXISTS WSA.ProductItemOrdered
DROP TABLE IF EXISTS WSA.Product
DROP TABLE IF EXISTS WSA.ProductBrand
DROP TABLE IF EXISTS WSA.ProductType
DROP TABLE IF EXISTS WSA.CustomerBasket
DROP TABLE IF EXISTS WSA.DeliveryMethod
DROP TABLE IF EXISTS WSA.OrderStatus
DELETE FROM [dbo].[__EFMigrationsHistory]
